Запуск скомпилированного файла под Астрой 1.6.10 завершается с ошибкой
Error loading Python lib '/tmp/_MEInEohE5/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEInEohE5/libpython3.8.so.1.0)
видимо нужно компилировать с правильной версией питона или окружения!

Обеспечить работоспособность при отсутствии файла с конфигурацией. В основном проблема с отсутствием секций, а далее дефолтные значения записываются нормально

Попробовать запустить программу под ненулевым мандатным уровнем (для общего понимания ситуации, формально нужен только "0")

Уточнить на какой адрес приходит квитанция на команду смены адреса интерфейса ЛВС, на старый или на новый? Нужно перезапускать поток с сокетом? Пока просто собщение о необхлдимости перезапуска программы!

Сделать логирование запуска/завершения, исключений, опционально запросов и полученных квитанций

Добавить в меню Справка пункт "О программе"

Почему при запуске "упакованного" приложения не из под рута получаем ошибку
Error accessing /tmp/_MEIJdURKs/main.py: No such file or directory

Как в Makefile сделать пересборку при изменении .py или .ui файлов, сейчас пересобриается только при удалении каталога dist

Сделать deb-пакет
